# Generated by Django 3.2.20 on 2024-03-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
                ('Usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rationproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.CharField(max_length=250)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=35)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('House_name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compliant', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=300)),
                ('Replay', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
