# Generated by Django 4.2.7 on 2024-03-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_district_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='suplyco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offcode', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('estd', models.CharField(max_length=50)),
                ('AREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
