# Generated by Django 3.2.20 on 2024-04-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cardholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='STATECENTER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.statecenter'),
            preserve_default=False,
        ),
    ]
