# Generated by Django 3.2.20 on 2024-04-16 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=20)),
                ('lastdate', models.DateField()),
                ('createddate', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rationproducts')),
                ('STATECENTRE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.statecenter')),
            ],
        ),
    ]
