# Generated by Django 3.2.20 on 2024-04-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ration_product_cardtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARDTYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rationcardtype')),
                ('RATIONPRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rationproducts')),
            ],
        ),
    ]
