# Generated by Django 3.2.22 on 2024-04-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ration_product_cardtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='complaints',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
