# Generated by Django 3.2.22 on 2024-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20240416_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationproducts',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
