# Generated by Django 3.2.22 on 2024-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rationproducts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='quantiy',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
